"""Offline analysis of recorded INMP441 audio.

Examples:

    python tools/audio/analyze.py
    python tools/audio/analyze.py --plots
    python tools/audio/analyze.py --plots --csv features.csv
    python tools/audio/analyze.py --nfft 4096

Recording names encode two concepts:

    off_01.wav
        state=off
        interference=clean

    fan_talking_01.wav
        state=fan
        interference=talking

    compressor_talking_02.wav
        state=compressor
        interference=talking

Timestamp prefixes generated by capture.py and trailing numeric indexes
are ignored.

The goal is to find features that distinguish:

    OFF / FAN / COMPRESSOR

while remaining stable when interference such as speech is added.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.io import wavfile
from scipy.signal import spectrogram


HERE = Path(__file__).resolve().parent
DEFAULT_RECORDINGS = HERE / "recordings"
DEFAULT_PLOTDIR = HERE / "plots"

DEFAULT_SAMPLE_RATE = 16000
DEFAULT_NFFT = 1024

DB_FLOOR = -120.0

PEAK_MIN_HZ = 100.0
PEAK_MAX_HZ = 4000.0

STATE_ORDER = ["off", "fan", "compressor"]
KNOWN_STATES = set(STATE_ORDER)

DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")
NUMBER_PATTERN = re.compile(r"^\d+$")


# ---------------------------------------------------------------------
# Spectral features
# ---------------------------------------------------------------------

# Original exploratory bands.
BANDS: list[tuple[str, float, float]] = [
    ("30-80", 30.0, 80.0),
    ("80-200", 80.0, 200.0),
    ("200-500", 200.0, 500.0),
    ("500-1k", 500.0, 1000.0),
    ("1k-2k", 1000.0, 2000.0),
    ("2k-4k", 2000.0, 4000.0),
    ("1100-1200", 1100.0, 1200.0),

    # Derived classifier-oriented bands.
    ("200-1200", 200.0, 1200.0),
    ("1500-4000", 1500.0, 4000.0),
]

# high/mech is expressed in dB:
#
#     1500-4000 dB - 200-1200 dB
#
# This is equivalent to a spectral power ratio in logarithmic form.
DERIVED_FEATURES = [
    "high/mech",
]

FEATURES = (
    ["RMS"]
    + [name for name, _, _ in BANDS]
    + DERIVED_FEATURES
)


# ---------------------------------------------------------------------
# Naming / labels
# ---------------------------------------------------------------------

@dataclass(frozen=True)
class Labels:
    state: str
    interference: str

    @property
    def condition(self) -> str:
        if self.interference == "clean":
            return self.state

        return f"{self.state}_{self.interference}"


def infer_labels(path: Path) -> Labels:
    tokens = []

    for token in path.stem.lower().split("_"):
        if not token:
            continue

        if DATE_PATTERN.match(token):
            continue

        if NUMBER_PATTERN.match(token):
            continue

        tokens.append(token)

    state_index = None

    for index, token in enumerate(tokens):
        if token in KNOWN_STATES:
            state_index = index
            break

    if state_index is None:
        return Labels(
            state="unknown",
            interference="_".join(tokens) or "unknown",
        )

    state = tokens[state_index]

    remainder = (
        tokens[:state_index]
        + tokens[state_index + 1 :]
    )

    interference = (
        "_".join(remainder)
        if remainder
        else "clean"
    )

    return Labels(
        state=state,
        interference=interference,
    )


# ---------------------------------------------------------------------
# Signal helpers
# ---------------------------------------------------------------------

def to_float(samples: np.ndarray) -> np.ndarray:
    """Normalize WAV samples to approximately [-1, 1)."""

    if samples.ndim > 1:
        samples = samples[:, 0]

    if np.issubdtype(samples.dtype, np.floating):
        return samples.astype(np.float64)

    info = np.iinfo(samples.dtype)

    if info.min == 0:
        midpoint = (info.max + 1) / 2.0

        return (
            samples.astype(np.float64) - midpoint
        ) / midpoint

    return (
        samples.astype(np.float64)
        / float(-info.min)
    )


def power_to_db(
    power: np.ndarray | float,
) -> np.ndarray | float:
    """Mean-square power -> dBFS."""

    amplitude = np.sqrt(
        np.maximum(power, 0.0)
    )

    return np.maximum(
        20.0
        * np.log10(
            np.maximum(amplitude, 1e-12)
        ),
        DB_FLOOR,
    )


def frame_signal(
    signal: np.ndarray,
    nperseg: int,
    noverlap: int,
) -> np.ndarray:
    """Create windows aligned with scipy.signal.spectrogram."""

    step = nperseg - noverlap

    count = (
        1
        + (signal.size - nperseg) // step
    )

    offsets = (
        step
        * np.arange(count)[:, None]
    )

    indexes = (
        offsets
        + np.arange(nperseg)[None, :]
    )

    return signal[indexes]


# ---------------------------------------------------------------------
# Analysis object
# ---------------------------------------------------------------------

@dataclass
class Analysis:
    path: Path

    state: str
    interference: str

    sample_rate: int
    duration: float

    times: np.ndarray
    freqs: np.ndarray
    power: np.ndarray

    rms_db: np.ndarray
    band_db: dict[str, np.ndarray]

    peak_hz: np.ndarray

    @property
    def condition(self) -> str:
        if self.interference == "clean":
            return self.state

        return (
            f"{self.state}_"
            f"{self.interference}"
        )

    def feature(self, name: str) -> np.ndarray:
        if name == "RMS":
            return self.rms_db

        if name == "high/mech":
            return (
                self.band_db["1500-4000"]
                - self.band_db["200-1200"]
            )

        return self.band_db[name]

    @property
    def mean_spectrum_db(self) -> np.ndarray:
        return power_to_db(
            self.power.mean(axis=1)
        )


# ---------------------------------------------------------------------
# Per-file analysis
# ---------------------------------------------------------------------

def analyse_file(
    path: Path,
    nfft: int,
    overlap: float,
) -> Analysis:

    sample_rate, raw = wavfile.read(path)

    signal = to_float(raw)

    if signal.size < nfft:
        raise ValueError(
            f"{path.name}: only "
            f"{signal.size} samples; "
            f"need at least {nfft}"
        )

    labels = infer_labels(path)

    # Remove recording-wide DC.
    signal = signal - signal.mean()

    noverlap = int(
        nfft * overlap
    )

    freqs, times, power = spectrogram(
        signal,
        fs=sample_rate,
        window="hamming",
        nperseg=nfft,
        noverlap=noverlap,
        detrend="constant",
        scaling="spectrum",
        mode="psd",
    )

    # ----------------------------------------------------------
    # True time-domain RMS.
    # ----------------------------------------------------------

    windows = frame_signal(
        signal,
        nfft,
        noverlap,
    )

    windows = (
        windows
        - windows.mean(
            axis=1,
            keepdims=True,
        )
    )

    rms_db = power_to_db(
        np.mean(
            windows * windows,
            axis=1,
        )
    )

    if rms_db.size != times.size:
        raise ValueError(
            f"{path.name}: framing mismatch: "
            f"{rms_db.size} RMS windows vs "
            f"{times.size} spectral windows"
        )

    # ----------------------------------------------------------
    # Spectral band power.
    # ----------------------------------------------------------

    band_db: dict[
        str,
        np.ndarray
    ] = {}

    for name, low, high in BANDS:
        mask = (
            (freqs >= low)
            & (freqs < high)
        )

        if not mask.any():
            band_db[name] = np.full(
                times.shape,
                DB_FLOOR,
            )

            continue

        band_power = power[
            mask,
            :
        ].sum(axis=0)

        band_db[name] = power_to_db(
            band_power
        )

    # ----------------------------------------------------------
    # Dominant peak.
    # ----------------------------------------------------------

    peak_mask = (
        (freqs >= PEAK_MIN_HZ)
        & (freqs <= PEAK_MAX_HZ)
    )

    peak_freqs = freqs[peak_mask]

    if peak_freqs.size:
        peak_indexes = np.argmax(
            power[peak_mask, :],
            axis=0,
        )

        peak_hz = peak_freqs[
            peak_indexes
        ]
    else:
        peak_hz = np.zeros(
            times.shape
        )

    return Analysis(
        path=path,

        state=labels.state,
        interference=labels.interference,

        sample_rate=sample_rate,
        duration=(
            signal.size
            / sample_rate
        ),

        times=times,
        freqs=freqs,
        power=power,

        rms_db=rms_db,
        band_db=band_db,

        peak_hz=peak_hz,
    )


# ---------------------------------------------------------------------
# Grouping
# ---------------------------------------------------------------------

def state_sort_key(
    state: str,
) -> tuple[int, str]:

    if state in STATE_ORDER:
        return (
            STATE_ORDER.index(state),
            state,
        )

    return (
        len(STATE_ORDER),
        state,
    )


def group_by_state(
    analyses: list[Analysis],
) -> dict[str, list[Analysis]]:

    grouped: dict[
        str,
        list[Analysis]
    ] = {}

    for analysis in analyses:
        grouped.setdefault(
            analysis.state,
            [],
        ).append(analysis)

    return dict(
        sorted(
            grouped.items(),
            key=lambda item:
                state_sort_key(item[0]),
        )
    )


def group_by_condition(
    analyses: list[Analysis],
) -> dict[str, list[Analysis]]:

    grouped: dict[
        str,
        list[Analysis]
    ] = {}

    for analysis in analyses:
        grouped.setdefault(
            analysis.condition,
            [],
        ).append(analysis)

    return grouped


# ---------------------------------------------------------------------
# Generic feature access
# ---------------------------------------------------------------------

def concatenate_feature(
    analyses: list[Analysis],
    feature: str,
) -> np.ndarray:

    return np.concatenate(
        [
            analysis.feature(feature)
            for analysis in analyses
        ]
    )


# ---------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------

def format_table(
    rows: list[list[str]],
    headers: list[str],
) -> str:

    widths = [
        len(header)
        for header in headers
    ]

    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(
                widths[index],
                len(cell),
            )

    def render(
        cells: list[str],
    ) -> str:

        return "  ".join(
            (
                cell.ljust(
                    widths[index]
                )
                if index == 0
                else cell.rjust(
                    widths[index]
                )
            )
            for index, cell
            in enumerate(cells)
        )

    lines = [
        render(headers),
        "  ".join(
            "-" * width
            for width in widths
        ),
    ]

    lines.extend(
        render(row)
        for row in rows
    )

    return "\n".join(lines)


def per_file_table(
    analyses: list[Analysis],
) -> str:

    headers = [
        "File",
        "State",
        "Interference",
        "s",
        "RMS",
        "30-80",
        "200-500",
        "500-1k",
        "1k-2k",
        "2k-4k",
        "1100-1200",
        "200-1200",
        "1500-4000",
        "high/mech",
        "peak Hz",
    ]

    rows = []

    for analysis in analyses:
        rows.append(
            [
                analysis.path.name,
                analysis.state,
                analysis.interference,
                f"{analysis.duration:.1f}",

                f"{np.median(analysis.rms_db):.1f}",

                f"{np.median(analysis.band_db['30-80']):.1f}",
                f"{np.median(analysis.band_db['200-500']):.1f}",
                f"{np.median(analysis.band_db['500-1k']):.1f}",
                f"{np.median(analysis.band_db['1k-2k']):.1f}",
                f"{np.median(analysis.band_db['2k-4k']):.1f}",
                f"{np.median(analysis.band_db['1100-1200']):.1f}",

                f"{np.median(analysis.band_db['200-1200']):.1f}",
                f"{np.median(analysis.band_db['1500-4000']):.1f}",

                f"{np.median(analysis.feature('high/mech')):.1f}",

                f"{np.median(analysis.peak_hz):.0f}",
            ]
        )

    return format_table(
        rows,
        headers,
    )


def condition_table(
    grouped: dict[
        str,
        list[Analysis],
    ],
) -> str:

    headers = [
        "Condition",
        "files",
        "s",
        "RMS",
        "30-80",
        "200-500",
        "500-1k",
        "1k-2k",
        "200-1200",
        "1500-4000",
        "high/mech",
    ]

    rows = []

    for condition, analyses in grouped.items():
        duration = sum(
            a.duration
            for a in analyses
        )

        row = [
            condition,
            str(len(analyses)),
            f"{duration:.0f}",
        ]

        for feature in [
            "RMS",
            "30-80",
            "200-500",
            "500-1k",
            "1k-2k",
            "200-1200",
            "1500-4000",
            "high/mech",
        ]:
            values = concatenate_feature(
                analyses,
                feature,
            )

            row.append(
                f"{np.median(values):.1f}"
            )

        rows.append(row)

    return format_table(
        rows,
        headers,
    )


# ---------------------------------------------------------------------
# Robust physical-state separation
# ---------------------------------------------------------------------

def state_margin_table(
    grouped: dict[
        str,
        list[Analysis],
    ],
) -> str:
    """Measure state separation while including interference.

    For each feature and each pair of physical states:

        lower state interval = P10 .. P90
        higher state interval = P10 .. P90

    margin:

        P10(high) - P90(low)

    Positive means the central 80% distributions do not overlap.
    Negative means they overlap by that many dB.

    The table reports the worst pairwise margin for each feature.
    """

    usable_states = [
        state
        for state in STATE_ORDER
        if state in grouped
    ]

    if len(usable_states) < 2:
        return (
            "(need at least two physical "
            "states to compare)"
        )

    rows = []

    for feature in FEATURES:
        intervals = {}

        for state in usable_states:
            values = concatenate_feature(
                grouped[state],
                feature,
            )

            intervals[state] = {
                "p10": float(
                    np.percentile(
                        values,
                        10,
                    )
                ),
                "median": float(
                    np.median(values)
                ),
                "p90": float(
                    np.percentile(
                        values,
                        90,
                    )
                ),
            }

        pair_margins = []

        for i in range(
            len(usable_states)
        ):
            for j in range(
                i + 1,
                len(usable_states),
            ):
                a = usable_states[i]
                b = usable_states[j]

                ia = intervals[a]
                ib = intervals[b]

                if (
                    ia["median"]
                    <= ib["median"]
                ):
                    low = ia
                    high = ib
                    pair = f"{a}->{b}"
                else:
                    low = ib
                    high = ia
                    pair = f"{b}->{a}"

                margin = (
                    high["p10"]
                    - low["p90"]
                )

                pair_margins.append(
                    (
                        margin,
                        pair,
                    )
                )

        worst_margin, worst_pair = min(
            pair_margins,
            key=lambda item: item[0],
        )

        medians = " / ".join(
            f"{state} "
            f"{intervals[state]['median']:.1f}"
            for state in usable_states
        )

        rows.append(
            [
                feature,
                medians,
                worst_pair,
                f"{worst_margin:+.1f}",
            ]
        )

    rows.sort(
        key=lambda row:
            float(row[3]),
        reverse=True,
    )

    return format_table(
        rows,
        [
            "Feature",
            "state medians dB",
            "worst pair",
            "P10/P90 margin dB",
        ],
    )


# ---------------------------------------------------------------------
# Interference invariance
# ---------------------------------------------------------------------

def interference_shift_table(
    analyses: list[Analysis],
) -> str:
    """Compare clean vs all interfered samples for each state."""

    rows = []

    for state in STATE_ORDER:
        clean = [
            a
            for a in analyses
            if (
                a.state == state
                and a.interference == "clean"
            )
        ]

        interfered = [
            a
            for a in analyses
            if (
                a.state == state
                and a.interference != "clean"
            )
        ]

        if not clean or not interfered:
            continue

        for feature in FEATURES:
            clean_values = concatenate_feature(
                clean,
                feature,
            )

            interference_values = concatenate_feature(
                interfered,
                feature,
            )

            clean_median = float(
                np.median(clean_values)
            )

            interference_median = float(
                np.median(
                    interference_values
                )
            )

            shift = (
                interference_median
                - clean_median
            )

            rows.append(
                [
                    state,
                    feature,
                    f"{clean_median:.1f}",
                    f"{interference_median:.1f}",
                    f"{shift:+.1f}",
                    f"{abs(shift):.1f}",
                ]
            )

    rows.sort(
        key=lambda row:
            float(row[5])
    )

    if not rows:
        return (
            "(need both clean and interference "
            "recordings for at least one state)"
        )

    return format_table(
        rows,
        [
            "State",
            "Feature",
            "clean",
            "interference",
            "shift",
            "|shift|",
        ],
    )


# ---------------------------------------------------------------------
# Temporal stability
# ---------------------------------------------------------------------

def rolling_stability(
    values: np.ndarray,
    times: np.ndarray,
    seconds: float,
) -> float:
    """Median rolling standard deviation over a time window."""

    if values.size < 2:
        return 0.0

    if times.size >= 2:
        step_seconds = float(
            np.median(
                np.diff(times)
            )
        )
    else:
        return float(
            np.std(values)
        )

    window = max(
        2,
        int(
            round(
                seconds
                / step_seconds
            )
        ),
    )

    if values.size < window:
        return float(
            np.std(values)
        )

    windows = (
        np.lib.stride_tricks
        .sliding_window_view(
            values,
            window,
        )
    )

    deviations = np.std(
        windows,
        axis=1,
    )

    return float(
        np.median(deviations)
    )


def stability_table(
    analyses: list[Analysis],
    seconds: float,
) -> str:
    """How stationary is each feature over a few seconds?

    Lower values mean the feature changes less over time.
    """

    rows = []

    selected_features = [
        "30-80",
        "200-1200",
        "500-1k",
        "1k-2k",
        "1500-4000",
        "high/mech",
    ]

    for state in STATE_ORDER:
        state_files = [
            a
            for a in analyses
            if a.state == state
        ]

        if not state_files:
            continue

        for feature in selected_features:
            values = [
                rolling_stability(
                    analysis.feature(
                        feature
                    ),
                    analysis.times,
                    seconds,
                )
                for analysis
                in state_files
            ]

            rows.append(
                [
                    state,
                    feature,
                    f"{np.median(values):.2f}",
                    f"{np.percentile(values, 90):.2f}",
                ]
            )

    return format_table(
        rows,
        [
            "State",
            "Feature",
            f"median {seconds:g}s std dB",
            "P90 file std dB",
        ],
    )


# ---------------------------------------------------------------------
# CSV
# ---------------------------------------------------------------------

def write_csv(
    path: Path,
    analyses: list[Analysis],
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    feature_names = FEATURES

    with path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as handle:

        writer = csv.writer(handle)

        writer.writerow(
            [
                "file",
                "state",
                "interference",
                "condition",
                "t",
            ]
            + feature_names
            + ["peak_hz"]
        )

        for analysis in analyses:
            for index, time in enumerate(
                analysis.times
            ):
                writer.writerow(
                    [
                        analysis.path.name,
                        analysis.state,
                        analysis.interference,
                        analysis.condition,
                        f"{time:.3f}",
                    ]
                    + [
                        f"{analysis.feature(feature)[index]:.2f}"
                        for feature
                        in feature_names
                    ]
                    + [
                        f"{analysis.peak_hz[index]:.1f}"
                    ]
                )


# ---------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------

def make_plots(
    grouped_states: dict[
        str,
        list[Analysis],
    ],
    analyses: list[Analysis],
    plotdir: Path,
    fmax: float,
) -> list[Path]:

    import matplotlib

    matplotlib.use("Agg")

    import matplotlib.pyplot as plt

    plotdir.mkdir(
        parents=True,
        exist_ok=True,
    )

    written: list[Path] = []

    # ----------------------------------------------------------
    # Average spectrum by physical state, including interference.
    # ----------------------------------------------------------

    figure, axis = plt.subplots(
        figsize=(11, 6)
    )

    for state, state_analyses in grouped_states.items():
        freqs = state_analyses[0].freqs

        spectra = [
            a.power.mean(axis=1)
            for a in state_analyses
        ]

        mean_power = np.mean(
            spectra,
            axis=0,
        )

        axis.plot(
            freqs,
            power_to_db(mean_power),
            linewidth=1.0,
            label=state,
        )

    axis.set_xlim(
        0,
        fmax,
    )

    axis.set_xlabel("Hz")
    axis.set_ylabel("dBFS")

    axis.set_title(
        "Average spectrum by physical AC state"
    )

    axis.grid(alpha=0.3)
    axis.legend()

    path = (
        plotdir
        / "spectrum_by_state.png"
    )

    figure.savefig(
        path,
        dpi=130,
        bbox_inches="tight",
    )

    plt.close(figure)
    written.append(path)

    # ----------------------------------------------------------
    # Per-file plots.
    # ----------------------------------------------------------

    for analysis in analyses:
        written.append(
            _plot_bands_over_time(
                plt,
                analysis,
                plotdir,
            )
        )

        written.append(
            _plot_spectrogram(
                plt,
                analysis,
                plotdir,
                fmax,
            )
        )

    return written


def _plot_bands_over_time(
    plt,
    analysis: Analysis,
    plotdir: Path,
) -> Path:

    figure, axis = plt.subplots(
        figsize=(11, 5)
    )

    axis.plot(
        analysis.times,
        analysis.rms_db,
        linewidth=1.4,
        label="RMS",
    )

    for feature in [
        "30-80",
        "200-1200",
        "500-1k",
        "1k-2k",
        "1500-4000",
    ]:
        axis.plot(
            analysis.times,
            analysis.feature(feature),
            linewidth=0.8,
            label=feature,
        )

    axis.set_xlabel("s")
    axis.set_ylabel("dBFS")

    axis.set_title(
        f"Features over time - "
        f"{analysis.path.name}"
    )

    axis.grid(alpha=0.3)

    axis.legend(
        ncol=3,
        fontsize=8,
    )

    path = (
        plotdir
        / f"bands_{analysis.path.stem}.png"
    )

    figure.savefig(
        path,
        dpi=130,
        bbox_inches="tight",
    )

    plt.close(figure)

    return path


def _plot_spectrogram(
    plt,
    analysis: Analysis,
    plotdir: Path,
    fmax: float,
) -> Path:

    figure, axis = plt.subplots(
        figsize=(11, 5)
    )

    mesh = axis.pcolormesh(
        analysis.times,
        analysis.freqs,
        power_to_db(
            analysis.power
        ),
        shading="auto",
        vmin=DB_FLOOR,
        vmax=-20.0,
    )

    axis.set_ylim(
        0,
        fmax,
    )

    axis.set_xlabel("s")
    axis.set_ylabel("Hz")

    axis.set_title(
        f"Spectrogram - "
        f"{analysis.path.name}"
    )

    figure.colorbar(
        mesh,
        ax=axis,
        label="dBFS",
        pad=0.01,
    )

    path = (
        plotdir
        / f"spectrogram_"
        f"{analysis.path.stem}.png"
    )

    figure.savefig(
        path,
        dpi=130,
        bbox_inches="tight",
    )

    plt.close(figure)

    return path


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:

    parser = argparse.ArgumentParser(
        description=(
            "Compare OFF/FAN/COMPRESSOR "
            "audio signatures while treating "
            "speech and other interference "
            "separately."
        )
    )

    parser.add_argument(
        "files",
        nargs="*",
        type=Path,
        help=(
            "WAV files or directories. "
            "Default: tools/audio/recordings"
        ),
    )

    parser.add_argument(
        "--nfft",
        type=int,
        default=DEFAULT_NFFT,
        help=(
            f"FFT/window size "
            f"(default: {DEFAULT_NFFT})"
        ),
    )

    parser.add_argument(
        "--overlap",
        type=float,
        default=0.5,
        help=(
            "Window overlap fraction "
            "(default: 0.5)"
        ),
    )

    parser.add_argument(
        "--stability-seconds",
        type=float,
        default=2.0,
        help=(
            "Window used for temporal "
            "stability analysis "
            "(default: 2.0 s)"
        ),
    )

    parser.add_argument(
        "--fmax",
        type=float,
        default=None,
        help=(
            "Highest plotted frequency "
            "(default: Nyquist)"
        ),
    )

    parser.add_argument(
        "--plots",
        action="store_true",
        help="Write PNG plots",
    )

    parser.add_argument(
        "--plotdir",
        type=Path,
        default=DEFAULT_PLOTDIR,
        help=(
            "Plot output directory "
            "(default: tools/audio/plots)"
        ),
    )

    parser.add_argument(
        "--csv",
        type=Path,
        default=None,
        help=(
            "Write per-window features "
            "to CSV"
        ),
    )

    return parser


def collect_files(
    args: argparse.Namespace,
) -> list[Path]:

    if args.files:
        paths: list[Path] = []

        for entry in args.files:
            if entry.is_dir():
                paths.extend(
                    sorted(
                        entry.glob("*.wav")
                    )
                )
            else:
                paths.append(entry)

        return paths

    return sorted(
        DEFAULT_RECORDINGS.glob(
            "*.wav"
        )
    )


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main(
    argv: list[str] | None = None,
) -> int:

    parser = build_parser()

    args = parser.parse_args(
        argv
    )

    if (
        args.nfft < 64
        or args.nfft
        & (args.nfft - 1)
    ):
        parser.error(
            "--nfft must be a power "
            "of two and at least 64"
        )

    if not (
        0.0
        <= args.overlap
        < 1.0
    ):
        parser.error(
            "--overlap must be in [0, 1)"
        )

    if args.stability_seconds <= 0:
        parser.error(
            "--stability-seconds "
            "must be > 0"
        )

    paths = collect_files(args)

    if not paths:
        print(
            f"No recordings found in "
            f"{DEFAULT_RECORDINGS}.\n\n"
            "Capture one with:\n"
            "  python "
            "tools/audio/capture.py "
            "COM9 --label off_01 "
            "--seconds 30",
            file=sys.stderr,
        )

        return 1

    analyses: list[Analysis] = []

    for path in paths:
        if not path.exists():
            print(
                f"warning: "
                f"{path} does not exist",
                file=sys.stderr,
            )

            continue

        try:
            analyses.append(
                analyse_file(
                    path,
                    args.nfft,
                    args.overlap,
                )
            )

        except (
            ValueError,
            OSError,
        ) as error:

            print(
                f"warning: {error}",
                file=sys.stderr,
            )

    if not analyses:
        print(
            "error: nothing could "
            "be analysed",
            file=sys.stderr,
        )

        return 1

    sample_rates = {
        a.sample_rate
        for a in analyses
    }

    if len(sample_rates) > 1:
        print(
            "warning: mixed sample rates: "
            f"{sorted(sample_rates)}",
            file=sys.stderr,
        )

    sample_rate = (
        analyses[0].sample_rate
    )

    fmax = (
        args.fmax
        or sample_rate / 2.0
    )

    resolution = (
        sample_rate
        / args.nfft
    )

    print()
    print(
        f"{len(analyses)} recording(s)   "
        f"{sample_rate} Hz   "
        f"N={args.nfft} "
        f"({resolution:.2f} Hz/bin, "
        f"{args.nfft / sample_rate * 1000:.0f} ms/window)   "
        f"Hamming   "
        f"overlap {args.overlap:.0%}"
    )

    print()
    print("Per file")
    print()
    print(
        per_file_table(
            analyses
        )
    )

    grouped_conditions = (
        group_by_condition(
            analyses
        )
    )

    print()
    print(
        "Per condition"
    )
    print(
        "(physical state + interference)"
    )
    print()
    print(
        condition_table(
            grouped_conditions
        )
    )

    grouped_states = (
        group_by_state(
            analyses
        )
    )

    print()
    print(
        "Physical-state separation"
    )
    print(
        "All interference variants are "
        "included in each OFF/FAN/"
        "COMPRESSOR population."
    )
    print(
        "Positive P10/P90 margin = "
        "robust non-overlap."
    )
    print()
    print(
        state_margin_table(
            grouped_states
        )
    )

    print()
    print(
        "Interference invariance"
    )
    print(
        "Smaller absolute shift is better."
    )
    print()
    print(
        interference_shift_table(
            analyses
        )
    )

    print()
    print(
        "Temporal stability"
    )
    print(
        "Lower rolling standard deviation "
        "means a more stationary feature."
    )
    print()
    print(
        stability_table(
            analyses,
            args.stability_seconds,
        )
    )

    if args.csv:
        write_csv(
            args.csv,
            analyses,
        )

        print()
        print(
            f"Wrote per-window "
            f"features to {args.csv}"
        )

    if args.plots:
        written = make_plots(
            grouped_states,
            analyses,
            args.plotdir,
            fmax,
        )

        print()
        print(
            f"Wrote {len(written)} "
            f"plot(s) to "
            f"{args.plotdir}"
        )

    print()

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )