"""Generate src/audio/GoldenVectors.h: fixed PCM windows + expected features.

Each vector is one 2048-sample window cut from recorded audio, with the
features the float64 reference (watson_ref.RefExtractor, i.e. the PC v2 math)
computes for it. The firmware's WATSON SELFTEST command runs the same windows
through the extractor on the ESP32 -- real FFT library, real FPU, real newlib
math -- and compares.

    python validation/make_golden.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

import dataset as ds
import watson_ref as ref

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "audio" / "GoldenVectors.h"

# (name, wav file, window start in seconds). Chosen to exercise every band:
# a running compressor+fan, a clean fan, an idle room, and a beep.
PICKS = [
    ("compressor_fan", "2026-09-30_103520_compressor_01.wav", 20.0),
    ("fan", "2026-09-30_104421_fan_01.wav", 20.0),
    ("off", "2026-09-30_102740_off_01.wav", 20.0),
]

FEATURE_FIELDS = [
    ("rms", "rms"), ("mid", "500-1k"), ("high", "1k-2k"),
    ("primary", "comp_primary"), ("lower", "comp_lower"),
    ("shoulder", "comp_shoulder"), ("upper", "comp_upper"),
    ("beep_band", "beep_band_power"), ("beep_peak", "beep_peak_hz"),
    ("beep_neighbour", "beep_neighbor_power"),
    ("beep_contrast", "beep_contrast_db"),
]


def beep_window() -> tuple[str, np.ndarray]:
    """The 2048 samples centred on the strongest tone in a reviewed beep."""
    record = next(r for r in ds.v2_records()
                  if r.event_type == "beep" and r.reviewed)
    samples = ref.load_wav(record.wav_path)
    extractor = ref.RefExtractor()
    best, best_at = -1e9, 0
    for start in range(0, samples.size - ref.NFFT, ref.HOP):
        w = extractor.analyse(samples[start:start + ref.NFFT])
        c = w.diagnostics["beep_contrast_db"]
        if c > best:
            best, best_at = c, start
    return "beep", samples[best_at:best_at + ref.NFFT]


def window_features(window: np.ndarray) -> dict:
    # A fresh extractor: one window of history, so 1k-2k_std is 0.
    w = ref.RefExtractor().analyse(window / ref.FULL_SCALE)
    values = dict(w.values)
    return {name: float(values[key]) for name, key in FEATURE_FIELDS}


def c_float(x: float) -> str:
    return f"{x:.9g}f"


def main() -> None:
    vectors = []
    for name, wav, at in PICKS:
        samples = ref.load_wav(ref.TOOLS / "recordings" / wav)
        start = int(at * ref.SAMPLE_RATE)
        vectors.append((name, samples[start:start + ref.NFFT]))
    vectors.append(beep_window())

    rng = np.random.default_rng(7)
    history = np.round(rng.normal(-55.0, 4.0, 62) * 1000) / 1000.0
    std_expected = float(np.std(history))

    lines = [
        "// Generated by validation/make_golden.py -- do not edit.",
        "//",
        "// Fixed 2048-sample windows of recorded audio (right-aligned 24-bit",
        "// samples, as the device delivers them) and the features the float64",
        "// reference computes for each. WATSON SELFTEST checks the firmware against",
        "// them. Tolerances are in SelfTest.cpp.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "namespace watson",
        "{",
        "    namespace golden",
        "    {",
        "        struct Expected",
        "        {",
        "            const char *name;",
        "            const int32_t *samples; // 2048",
    ]
    lines += [f"            float {n};" for n, _ in FEATURE_FIELDS]
    lines += ["        };", ""]

    for name, window in vectors:
        data = np.round(window).astype(np.int64)
        lines.append(f"        static const int32_t kSamples_{name}[2048] = {{")
        for i in range(0, 2048, 8):
            lines.append("            " + ", ".join(str(int(v)) for v in data[i:i + 8]) + ",")
        lines.append("        };")
        lines.append("")

    lines.append("        static const Expected kVectors[] = {")
    for name, window in vectors:
        feats = window_features(np.round(window))
        lines.append("            {")
        lines.append(f'                "{name}", kSamples_{name},')
        lines.append("                " + ", ".join(c_float(feats[n]) for n, _ in FEATURE_FIELDS))
        lines.append("            },")
    lines.append("        };")
    lines.append("")
    lines.append("        // Population std check (the fan stationarity statistic).")
    lines.append("        static const float kStdInput[62] = {")
    for i in range(0, 62, 8):
        lines.append("            " + ", ".join(c_float(float(v)) for v in history[i:i + 8]) + ",")
    lines.append("        };")
    lines.append(f"        static const float kStdExpected = {c_float(std_expected)};")
    lines += ["    } // namespace golden", "} // namespace watson", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(vectors)} vectors)")


if __name__ == "__main__":
    main()
